### ISSUE TITLE
Publish NRV dApp on neo.org

### ISSUE THREAD

**Issue by brianlenz** [NarrativeNetwork/tokensale-neo-smartcontract#2]
We should get listed on the NEO dApp list:

https://neo.org/dapps?culture=en-us

Steps to follow to create PR and get listed:

https://github.com/neo-project/neo.org/tree/master/NeoWeb/Views/DApps

**Comment by brianlenz** [comment]
It's now moved here: http://ndapp.org/

Steps to add here: https://github.com/ndapp/WebSite

@ted-oneill, it looks like we'll need a 600x300 logo to include.

We have to stick to the general structure of each app block, but we can control the content that goes in it. I'll be happy to handle submitting the PR once we know what we want it to look like.

Thanks!

**Comment by brianlenz** [comment]
Here's the source file for the HTML:

https://github.com/ndapp/WebSite/blob/master/WebSite/wwwroot/index.html

Here's a template for the HTML:

```
<div class="dapp">
    <img data-original="images/Narrative.png">
    <div>
        <h3 class="mt-2 mb-1">Narrative</h3>
        <small class="d-block mb-2">by <a href="https://www.narrative.network" target="_blank">Narrative Team</a></small>
        <p class="description">Narrative is a self-sustaining content network where members are in charge, users get paid, and the world’s best content, on every subject imaginable, is easy to find.</p>
        <div class="link">
            <a href="https://www.narrative.network" target="_blank">Website</a>
            <a href="https://community.narrative.network" target="_blank">Community</a>
            <a href="https://twitter.com/narrative_hq" target="_blank">Twitter</a>
            <a href="https://t.me/narrativenetwork" target="_blank">Telegram</a>
            <a href="https://github.com/NarrativeNetwork" target="_blank">GitHub</a>
        </div>
    </div>
</div>
```

Assuming you're good with this, all we would need is the 600x300 image to display and the description to use. I pulled that sentence from the intro paragraph of the WP...

**Comment by ted-oneill** [comment]
Cool-- I'll get the image. Please change "ecosystem" to "network" in the description though.

**Comment by ted-oneill** [comment]
Image:
https://assets.narrative.network/images/narrative-dapp-logo.png

**Comment by brianlenz** [comment]
Sure thing! Are you good with it otherwise? Here's what it looks like as written:

![screen shot 2018-02-06 at 8 12 31 am](https://user-images.githubusercontent.com/2305088/35870069-8a9bfd36-0b15-11e8-8a83-29cad591fddb.png)

**Comment by brianlenz** [comment]
PR created (first one on the new project):

https://github.com/ndapp/WebSite/pull/1

Will keep this open until we are officially listed.

Note: even though the screenshot says "ecosystem", the PR properly contains "network".

**Comment by brianlenz** [comment]
PR merged. Website updated:

http://ndapp.org/
