### ISSUE TITLE
Redundant method "circulation"

### ISSUE THREAD

**Issue by evanlenz** [NarrativeNetwork/tokensale-neo-smartcontract#4]
What is the point of this method, since it apparently does exactly the same thing as totalSupply? Since it's not needed for NEP5, should it be removed?

https://github.com/NarrativeNetwork/tokensale-neo-smartcontract/blob/182d46bec2381f247d31fb782f0cabb8709ecd67/ico_template.py#L85

**Comment by brianlenz** [comment]
Hmmm. That, I don't know the answer to. I know that `mintTokens` is a "special" operation that is not part of NEP-5, but it's a "standard" adopted by the Neon wallet for participating in crowd sales. I don't know if this `circulation` operation is similar. I agree it's completely redundant, but I wonder if any clients might use it (e.g. legacy wallets)?

**Comment by brianlenz** [comment]
Since it's part of NEX's neo-ico-template, I'm inclined to leave it as-is since it's not hurting anything.

**Comment by evanlenz** [comment]
Makes sense. Better safe than sorry.
